#!/usr/bin/env bash
#script to change landing page of localhost
sudo apt-get update -y

sudo apt-get install -y nginx

echo "Holberton School for the win!" | sudo tee /var/www/html/index.nginx-debian.html

sudo service nginx restart
