#!/usr/bin/env bash
# Script to install Nginx, set up a custom 404 page, and add a redirect.

# Update package lists and install Nginx
apt-get -y update
apt-get install -y nginx

# Overwrite the default Nginx page (optional)
echo "Holberton School for the win!" > /var/www/html/index.html

# Create the custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Re-create the default Nginx configuration
cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    # Redirection location
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=7qZl_5xHoBw&t=1358s&ab_channel=PowerfulJRE;
    }

    # Custom error page for 404
    error_page 404 /404.html;

    # This ensures custom 404 works when accessing /xyz
    location /xyz {
        return 404;
    }
}
EOF

# Link the new configuration to sites-enabled
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Test and reload the Nginx configuration
sudo nginx -t && /etc/nginx/sites-available/defaultsudo service nginx restart 
